import React from "react";
import styles from "./styles.module.scss";
const OurWork = () => {
  const ourWorkData = {
    heading:"",
    cards:[
      {
        img:{
          url:"../../public/image/OurWork/work_1.png",
          alt:"work_1"
        }
      },
      {
        img:{
          url:"../../public/image/OurWork/work_2.png",
          alt:"work_2"
        }
      },
      {
        img:{
          url:"../../public/image/OurWork/work_1.png",
          alt:"work_1"
        }
      },
      {
        img:{
          url:"../../public/image/OurWork/work_2.png",
          alt:"work_2"
        }
      },
      {
        img:{
          url:"../../public/image/OurWork/work_1.png",
          alt:"work_1"
        }
      },
      {
        img:{
          url:"",
          alt:""
        }
      },
      {
        img:{
          url:"",
          alt:""
        }
      },
      {
        img:{
          url:"",
          alt:""
        }
      },
      {
        img:{
          url:"",
          alt:""
        }
      },
      {
        img:{
          url:"",
          alt:""
        }
      },
      {
        img:{
          url:"",
          alt:""
        }
      },
      {
        img:{
          url:"",
          alt:""
        }
      },
      {
        img:{
          url:"",
          alt:""
        }
      },
    ]
  }
  return <div>OurWork</div>;
};

export default OurWork;
